# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run lint
    npm run build
  displayName: 'build'

- script: |
    git config --global user.email "willis.rh@gmail.com"
    git config --global user.name "Richard Willis"
    git config remote.origin.url https://badsyntax:"$token"@github.com/gr-20/20-20-project.com.git
    git commit -m "Publishing GitHub Pages [skip ci]"
    npm run deploy
  env:
    token: $(github_token)
  displayName: 'Deploy to GitHub pages'